# applog.properties - CNT 4714 Spring 2026
# HIDDEN: For application-level logging to operationslog only. Do not expose to end-users.
# Used by Main Application for transaction logging.

jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/operationslog
jdbc.username=project3app
jdbc.password=project3app
